// <auto-generated />
namespace DataMapper.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.0")]
    public sealed partial class EditionsLoansBorrower : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(EditionsLoansBorrower));
        
        string IMigrationMetadata.Id
        {
            get { return "202001122143504_Editions-Loans-Borrower"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
