// <auto-generated/>
namespace DataMapper.Migrations
{
    using System;
    using System.Data.Entity.Migrations;
    
    public partial class Addedloanstoedition : DbMigration
    {
        public override void Up()
        {
            DropForeignKey("dbo.Books", "Loan_Id", "dbo.Loans");
            DropIndex("dbo.Books", new[] { "Loan_Id" });
            CreateTable(
                "dbo.LoanBooks",
                c => new
                    {
                        Loan_Id = c.Int(nullable: false),
                        Book_Id = c.Int(nullable: false),
                    })
                .PrimaryKey(t => new { t.Loan_Id, t.Book_Id })
                .ForeignKey("dbo.Loans", t => t.Loan_Id, cascadeDelete: true)
                .ForeignKey("dbo.Books", t => t.Book_Id, cascadeDelete: true)
                .Index(t => t.Loan_Id)
                .Index(t => t.Book_Id);
            
            DropColumn("dbo.Books", "Loan_Id");
        }
        
        public override void Down()
        {
            AddColumn("dbo.Books", "Loan_Id", c => c.Int());
            DropForeignKey("dbo.LoanBooks", "Book_Id", "dbo.Books");
            DropForeignKey("dbo.LoanBooks", "Loan_Id", "dbo.Loans");
            DropIndex("dbo.LoanBooks", new[] { "Book_Id" });
            DropIndex("dbo.LoanBooks", new[] { "Loan_Id" });
            DropTable("dbo.LoanBooks");
            CreateIndex("dbo.Books", "Loan_Id");
            AddForeignKey("dbo.Books", "Loan_Id", "dbo.Loans", "Id");
        }
    }
}
