// <auto-generated/>
namespace DataMapper.Migrations
{
    using System;
    using System.Data.Entity.Migrations;
    
    public partial class Smallchanges : DbMigration
    {
        public override void Up()
        {
            AlterColumn("dbo.Loans", "ReturnDate", c => c.DateTime());
        }
        
        public override void Down()
        {
            AlterColumn("dbo.Loans", "ReturnDate", c => c.DateTime(nullable: false));
        }
    }
}
